server:
  port: 8080
  servlet:
    context-path: /api/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gpt_learn
    username: ${db.username}
    password: ${db.pass}
  jpa:
    hibernate:
      ddl-auto: create

openai:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com/v1/chat/completions
    key: your-api-key