server:
  port: 8080
  servlet:
    context-path: /api/


spring:
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: "db/changelog/db.changelog-master.xml"
  datasource:
    username: ${db.username}
    password: ${db.pass}
    url: jdbc:mysql://localhost:3306/gpt_learn
  mvc:
    log-resolved-exception: false

springdoc:
  api-docs:
    path: /api-docs

app:
  openai:
    model: gpt-4-1106-preview
    api:
      url: https://api.openai.com/v1/chat/completions
      key: ${openai.api.key}
  jwt:
    secret: ${jwt.secret}
    lifetime: ${jwt.lifetime}


