server:
  port: 8080
  servlet:
    context-path: /api/


spring:
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: "db/changelog/db.changelog-master.xml"
  datasource:
    username: ${DB_USER}
    password: ${DB_PW}
    url: ${DB_URL}
  mvc:
    log-resolved-exception: false

springdoc:
  api-docs:
    path: /api-docs

app:
  openai:
    model: gpt-4-1106-preview
    api:
      url: https://api.openai.com/v1/chat/completions
      key: ${OPENAI_API_KEY}
  jwt:
    secret: ${JWT_SECRET}
    lifetime: ${JWT_LIFETIME}


